BookStore/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('index/', include('index.urls')),
]

index/urls.py
# -*- coding: utf-8 -*-
# @Time    : 2021/9/30 21:37
# @Author  : Cxiaobai
# @Email   : 494158341@qq.com
# @File    : urls.py
# @Software: PyCharm

from django.urls import path

from . import views

app_name = 'index'
urlpatterns = [
    path('', views.index, name='index'),
    path('login/', views.login_view, name="login"),
    path('logout/', views.logout_view, name='logout'),
    path('register/', views.register_view, name='register'),
    path('title_search_result/', views.title_search_result, name='title_search_result'),
    path('book_table/', views.book_table, name='book_table'),
    path('add_book/', views.add_book, name='add_book'),
    path('delete_book/', views.delete_book, name='delete_book'),
    path('name_form/', views.get_name, name='name_form'),
    path('cx/', views.cx, name='cx'),
    path('dy/', views.dy, name='dy'),
    path('dj/', views.dj, name='dj'),
    path('mf/', views.mf, name='mf'),
    path('xs/', views.xs, name='xs'),
    path('description/', views.click_title, name='description'),
    path('test/', views.TestView.as_view(), name='test'),
]

index/templates/index/add_book.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>增加书籍</title>
</head>
<body>
<form action="/index/add_book/" method="post">
    {% csrf_token %}
    <p id="add_title">
        title:<input type="text" name="title">
    </p>
    <p id="add_price">
        price:<input type="text" name="price">
    </p>
    <p id="retail_price">
        retail_price:<input type="text" name="retail_price">
    </p>
    <p id="public">
        public:<input type="text" name="public">
    </p>
    <p id="submit">
        <input type="submit" value="提交">

    </p>
</form>
<a href="{% url 'index:book_table' %}"> 返回书籍列表</a>
</body>
</html>

index/templates/index/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% block style %}
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'index/base_style.css' %}">
    {% endblock style %}

    <meta charset="UTF-8">
    {% block title %}
    <title>Title</title>
    {% endblock title %}
</head>
<body>
{% block header %}
<header>
    <div class="header_box">
        <div class="header_edu">
            <p><a href="http://www.cdutetc.cn/" target="_blank">成理工程</a></p>
        </div>
        <div class="header_name">
            <p>半亩书店</p>
        </div>
        <div class="login_url">
            <h3>
                <a href="{% url 'index:login' %}">Login</a>
            </h3>
        </div>
        <div class="search">
            <form action="/index/title_search_result" method="get">
                <input type="text" name="title" placeholder="书名">
                <input type="submit" value="搜索">
            </form>
        </div>
    </div>
</header>
{% endblock header %}

{% block nav %}
<nav>
    <div class="nav_list">
        <ul>
            <li>
                <a href="{% url 'index:index' %}">主页</a>
            </li>
            <li>
                <a href="{% url 'index:cx' %} ">畅销榜</a>
            </li>
            <li>
                <a href="{% url 'index:dy' %} ">订阅榜</a>
            </li>
            <li>
                <a href="{% url 'index:dj' %} ">点击榜</a>
            </li>
            <li>
                <a href="{% url 'index:mf' %} ">免费榜</a>
            </li>
            <li>
                <a href="{% url 'index:xs' %} ">新书榜</a>
            </li>
        </ul>
    </div>
    <hr>
</nav>
{% endblock nav %}

{% block main %}
<main>

</main>
{% endblock main %}

{% block footer %}
<footer style="float:left">
    <hr>
    <div class="desc">
        <p style="font-size:1rem"><strong>Powered by Django</strong></p>
        <p>The web framework for perfectionists with deadlines</p>
    </div>
    <div class="image">
        <ul>
            <li><img src="{% static 'index/images/学校1.jpg' %}" width="380" height="200" title="成理工程"></li>
            <li><img src="{% static 'index/images/学校2.jpg' %}" width="380" height="200" title="成理工程"></li>
            <li><img src="{% static 'index/images/学校3.jpg' %}" width="380" height="200" title="成理工程"></li>
            <li><img src="{% static 'index/images/学校4.jpg' %}" width="380" height="200" title="成理工程"></li>
            <li><img src="{% static 'index/images/学校5.jpg' %}" width="380" height="200" title="成理工程"></li>
        </ul>
    </div>
    <hr>
</footer>
{% endblock footer %}
</body>
</html>

index/templates/index/book_name.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{#{% for book_name in BOOKs %}#}
{#    <p>{{ book_name.title }}</p>#}
{#{% endfor %}#}
{{ BOOKs }}
</body>
</html>

index/templates/index/book_table.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>书籍信息表</title>
</head>
<body>
<table border="1">
    <tr>
        <th>id</th>
        <th>title</th>
        <th>price</th>
        <th>retail_price</th>
        <th>public</th>
        <th>option</th>
    </tr>
    {% for book in all_book %}
        <tr>
            <td>{{ book.id }}</td>
            <td>{{ book.title }}</td>
            <td>{{ book.price }}</td>
            <td>{{ book.retail_price }}</td>
            <td>{{ book.pub.pubname }}</td>
            <td>
                <a href="/index/update_book/{{ book.id }}">更新</a>
                <a href="/index/delete_book/{{ book.id }}">删除</a>
            </td>
        </tr>
    {% endfor %}
</table>
<p>
    <a href="{% url 'index:add_book' %}">添加书籍</a>
    <a href="{% url 'index:delete_book' %}">删除书籍</a>
</p>
</body>
</html>

index/templates/index/delete_book.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>删除书籍</title>
</head>
<body>
<form action="/index/delete_book/" method="post">
    {% csrf_token %}
    <p>
        书籍名称：<input type="text" name="title">
        {{ error }}
    </p>
    <p>
        <input type="submit" value="提交">
        <a href="{% url 'index:book_table' %}"> 返回书籍列表</a>
    </p>
</form>
</body>
</html>

index/templates/index/index.html
{% extends 'index/base.html' %}
<html lang="en">
<head>
    {% block style %}
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'index/base_style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'index/index_style.css' %}">
    {% endblock style %}
    <meta charset="UTF-8">
    {% block title %}
    <title>主页</title>
    {% endblock title %}
</head>
<body>
{% block main%}
<main>

</main>
{% endblock main%}
</body>
</html>

index/templates/index/login.html
{% extends 'index/base.html' %}
<html lang="en">
<head>
    {% block style %}
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'index/base_style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'index/login_style.css' %}">
    {% endblock style %}
    <meta charset="UTF-8">
    {% block title %}
    <title>Login</title>
    {% endblock title %}
</head>

<body>
{% block main %}
<main>
    <div class="login_box">
        <div class="login_pictures" style="">

        </div>
        <div class="login_form">
            <form action="/index/login/" method="post">
                {% csrf_token %}
                <p class="login_name">
                    <input type="text" name="username" value="{{ username }}">
                    <span>{{ error }}</span>
                </p>
                <p class="login_pwd">
                    <input type="password" name="password" value="{{ password }}">
                </p>
                <p class="login_rem_name">
                    记住账号<input type="checkbox" name="isSaved">
                </p>
                <p class="login">
                    <input type="submit" value="登录">
                </p>
            </form>
            <p class="register">
                没有账号？点击<a href="{% url 'index:register' %}">注册</a>
            </p>
        </div>
    </div>
</main>
{% endblock main %}
</body>
</html>

index/templates/index/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>注册</title>
</head>
<body>
<form action="/index/register/" method="post">
    {% csrf_token %}
    <p>
        用户名<input type="text" name="username" value="{{  username }}">
        <span>{{ username_error }}</span>
    </p>
    <p>
        密码<input type="password" name="password" value="{{ password }}">
        <span>{{ password_error }}</span>
    </p>
    <p>
        再次输入密码<input type="password" name="password_again" value="{{ password_again }}">
        <span>{{ password_again_error }}</span>
    </p>
    <input type="submit" value="注册">
</form>
</body>
</html>

index/templates/index/title_search.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>搜索</title>
</head>
<body>
<form action="/index/title_search_result" method="get">
    <p>
        {{ form }}
        <input type="text" name="title" placeholder="书名">
        <input type="submit" value="search_title">
    </p>
</form>
{% if error %}
    {{ error.0 }}
{% endif %}
</body>
</html>

index/templates/index/title_search_result.html
{% extends 'index/base.html' %}
<html lang="en">
<head>
    {% block style %}
        {% load static %}
        <link rel="stylesheet" type="text/css" href="{% static 'index/base_style.css' %}">
    {% endblock style %}
    <meta charset="UTF-8">
    {% block title %}
        <title>搜索结果</title>
    {% endblock title %}
</head>
<body>
{% block main %}
    <main>
        <h1>搜索结果</h1>
        {% if title %}
            {% for i in title %}
                <p style="font-size: 20px">书名：{{ i.title }}</p>
                <img src="{{ i.img_ul }}" alt="">
                <p>{{ i.description }}</p>
                <p>作者：{{ i.author }}</p>
            {% endfor %}
        {% else %}
            {{ error }}
        {% endif %}
        {{ form }}
    </main>
{% endblock main %}

</body>
</html>

index/templates/index/新书榜.html
{% extends 'index/base.html' %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block title%}
    <title>新书榜</title>
    {% endblock title %}
</head>
<body>
{% block main %}
<main>

</main>
{% endblock main%}
</body>
</html>

index/templates/index/点击榜.html
{% extends 'index/base.html' %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block title%}
    <title>点击榜</title>
    {% endblock title %}
</head>
<body>
{% block main %}

<main>

</main>
{% endblock main%}
</body>
</html>

index/templates/index/畅销榜.html
{% extends 'index/base.html' %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block title%}
    <title>畅销榜</title>
    {% endblock title %}
</head>
<body>
{% block main %}
<main>

</main>
{% endblock main%}
</body>
</html>

index/templates/index/订阅榜.html
{% extends 'index/base.html' %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block title%}
    <title>订阅榜</title>
    {% endblock title %}
</head>
<body>
{% block main %}
<main>

</main>
{% endblock main%}
</body>
</html>