BookStore/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('index/', include('index.urls')),
]

index/urls.py
# -*- coding: utf-8 -*-
# @Time    : 2021/9/30 21:37
# @Author  : Cxiaobai
# @Email   : 494158341@qq.com
# @File    : urls.py
# @Software: PyCharm

from django.urls import path

from . import views

app_name = 'index'
urlpatterns = [
    path('', views.index, name='index'),
    path('login/', views.login_view, name="login"),
    path('logout/', views.logout_view, name='logout'),
    path('register/', views.register_view, name='register'),
    path('title_search_result/', views.title_search_result, name='title_search_result'),
    path('book_table/', views.book_table, name='book_table'),
    path('add_book/', views.add_book, name='add_book'),
    path('delete_book/', views.delete_book, name='delete_book'),
    path('name_form/', views.get_name, name='name_form'),
    path('cx/', views.cx, name='cx'),
    path('dy/', views.dy, name='dy'),
    path('dj/', views.dj, name='dj'),
    path('mf/', views.mf, name='mf'),
    path('xs/', views.xs, name='xs'),
    path('description/', views.click_title, name='description'),
    path('test/', views.TestView.as_view(), name='test'),
]

bookstore/index/templates/index/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% block style %}
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'index/base_style.css' %}">
    <link rel="icon" href="{% static 'index/images/学校.ico' %}">
    {% endblock style %}

    <meta charset="UTF-8">
    {% block title %}
    <title>Title</title>
    {% endblock title %}
</head>
<body>
{% block header %}
<header>
    <div class="header_box">
        <a class="header_edu" href="http://www.cdutetc.cn/" target="_blank" title="成都理工大学工程技术学院">成理工程</a>
        <a class="header_title" href="{% url 'index:index' %}" title="主页">半亩书店</a>
        <div class="header_search">
            <form action="/index/title_search_result" method="get">
                <input type="text" name="title" placeholder="书名">
                <input type="submit" value="搜索">
            </form>
        </div>
        <a class="header_login" href="{% url 'index:login' %}" title="登录">Login</a>

    </div>
</header>
{% endblock header %}

{% block nav %}
<nav>
    <div class="nav_list">
        <ul>
            <li>
                <a href="{% url 'index:cx' %} ">畅销榜</a>
            </li>
            <li>
                <a href="{% url 'index:dy' %} ">订阅榜</a>
            </li>
            <li>
                <a href="{% url 'index:dj' %} ">点击榜</a>
            </li>
            <li>
                <a href="{% url 'index:mf' %} ">免费榜</a>
            </li>
            <li>
                <a href="{% url 'index:xs' %} ">新书榜</a>
            </li>
        </ul>
    </div>
    <hr>
</nav>
{% endblock nav %}

{% block main %}
<main>

</main>
{% endblock main %}

{% block footer %}
<footer style="float:left">
    <hr>
    <div class="desc">
        <p style="font-size:1rem"><strong>Powered by Django</strong></p>
        <p>The web framework for perfectionists with deadlines</p>
    </div>
    <div class="image">
        <ul>
            <li><img src="{% static 'index/images/学校1.jpg' %}" width="370" height="200" title="成理工程"></li>
            <li><img src="{% static 'index/images/学校2.jpg' %}" width="380" height="200" title="成理工程"></li>
            <li><img src="{% static 'index/images/学校3.jpg' %}" width="380" height="200" title="成理工程"></li>
            <li><img src="{% static 'index/images/学校4.jpg' %}" width="380" height="200" title="成理工程"></li>
            <li><img src="{% static 'index/images/学校5.jpg' %}" width="380" height="200" title="成理工程"></li>
        </ul>
    </div>
    <hr>
</footer>
{% endblock footer %}
</body>
</html>

bookstore/index/templates/index/index.html
{% extends 'index/base.html' %}
<html lang="en">
<head>
    {% block style %}
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'index/base_style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'index/index_style.css' %}">
    <link rel="icon" href="{% static 'index/images/学校.ico' %}">
    {% endblock style %}
    <meta charset="UTF-8">
    {% block title %}
    <title>主页</title>
    {% endblock title %}
</head>
<body>
{% block main%}
<main>

</main>
{% endblock main%}
</body>
</html>

bookstore/index/templates/index/login.html
{% extends 'index/base.html' %}
<html lang="en">
<head>
    {% block style %}
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'index/base_style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'index/login_style.css' %}">
    <link rel="icon" href="{% static 'index/images/学校.ico' %}">
    {% endblock style %}
    <meta charset="UTF-8">
    {% block title %}
    <title>Login</title>
    {% endblock title %}
</head>

<body>
{% block nav %}
{% endblock nav %}

{% block main %}
<main>
    <div class="login">
        <div class="login_pictures">
            <img src="{% static 'index/images/login.jpg' %}">
        </div>
        <div class="login_box">
            <div class="login_box_title">
                <p>穷究于理</p>
                <p>成就于工</p>
            </div>
            <div class="login_box_form">
                <form action="/index/login/" method="post">
                    {% csrf_token %}
                    {{ form }}
                    <p>{{ error }}</p>
                    <p class="login_bot">
                        <input type="submit" value="登录">
                    </p>
                </form>
            </div>
            <p class="register">
                没有账号？点击<a href="{% url 'index:register' %}">注册</a>
            </p>
        </div>
    </div>
</main>
{% endblock main %}
</body>
</html>

bookstore/index/templates/index/register.html
{% extends 'index/base.html' %}
<html lang="en">
<head>
    {% block style %}
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'index/register_style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'index/base_style.css' %}">
    <link rel="icon" href="{% static 'index/images/学校.ico' %}">
    {% endblock style %}
    <meta charset="UTF-8">
    {% block title %}
    <title>注册</title>
    {% endblock title %}
</head>
<body>
{% block nav %}
{% endblock nav %}
{% block main %}
<div class="register">
    <div class="register_image">
        <img src="{% static 'index/images/学校8.jpg' %}">
    </div>
    <form method="post" class="register_box">
        {% csrf_token %}
        {{ form }}
        {{ password_again_error }}
        {{ username_error }}
        <input type="submit" value="注册">
    </form>
</div>
{% endblock main %}
</body>
</html>

bookstore/index/templates/index/title_search_result.html
{% extends 'index/base.html' %}
<html lang="en">
<head>
    {% block style %}
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'index/base_style.css' %}">
    {% endblock style %}
    <meta charset="UTF-8">
    {% block title %}
    <title>搜索结果</title>
    {% endblock title %}
</head>
<body>
{% block main %}
<main>
    <h1>搜索结果</h1>
    {% if book %}
    {% for i in book %}
    <p>书名：{{ i.title }}</p>
    <p><img src="{{ i.img_ul }}"></p>
    <p>作者：{{ i.author }}</p>
    {% endfor %}
    {% else %}
    {{ error }}
    {% endif %}
    {{ form }}
</main>
{% endblock main %}

</body>
</html>

bookstore/index/templates/index/免费榜.html
{% extends 'index/base.html' %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block style %}
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'index/base_style.css' %}">
    <link rel="icon" href="{% static 'index/images/学校.ico' %}">
    {% endblock style %}
    {% block title%}
    <title>免费榜</title>
    {% endblock title %}
</head>
<body>

{% block main %}
<main>
    <div class="book_body">
        <div class="book_box_all" style="margin-left:250px;margin-right:250px">
            {% for p in page %}
            <div class="book_box" style="display:block;margin:15px;border:1px solid black;width:200px;float:left;height:330px">
                <h2 style="display:block;padding:5px;">
                    <a href="{% url 'index:description' %}" style="text-decoration:none;color:black">{{ p.title }}</a>
                </h2>
                <img src="{{ p.img_ul }} " style="padding-left:36px">
                <p style="padding-left:50px;font-size:10px"><strong>{{ p.author }}</strong></p>
            </div>
            {% endfor %}
        </div>
        <div class="fy" style="display:block;margin-left:750px;margin-top:10px;margin-bottom:10px;float:left">
            {% if page.has_previous %}
            <a href="/index/mf?page={{ page.previous_page_number }}">上一页</a>
            {% else %}
            上一页
            {% endif %}
            {% for p in paginator.page_range %}
            {% if p == page.number %}
            {{ p }}
            {% else %}
            <a href="/index/mf?page={{ p }}">{{ p }}</a>
            {% endif %}
            {% endfor %}
            {% if page.has_next %}
            <a href="/index/mf?page={{ page.next_page_number }}">下一页</a>
            {% else %}
            下一页
            {% endif %}
        </div>
    </div>
</main>
{% endblock main%}

</body>
</html>

bookstore/index/templates/index/新书榜.html
{% extends 'index/base.html' %}
<html lang="en">
<head>
    <meta charset="UTF-8">
        {% block style %}
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'index/base_style.css' %}">
    <link rel="icon" href="{% static 'index/images/学校.ico' %}">
    {% endblock style %}
    {% block title%}
    <title>新书榜</title>
    {% endblock title %}
</head>
<body>
{% block main %}
<main>

</main>
{% endblock main%}
</body>
</html>

bookstore/index/templates/index/点击榜.html
{% extends 'index/base.html' %}
<html lang="en">
<head>
    <meta charset="UTF-8">
        {% block style %}
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'index/base_style.css' %}">
    <link rel="icon" href="{% static 'index/images/学校.ico' %}">
    {% endblock style %}
    {% block title%}
    <title>点击榜</title>
    {% endblock title %}
</head>
<body>
{% block main %}

<main>

</main>
{% endblock main%}
</body>
</html>

bookstore/index/templates/index/畅销榜.html
{% extends 'index/base.html' %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block style %}
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'index/base_style.css' %}">
    <link rel="icon" href="{% static 'index/images/学校.ico' %}">
    {% endblock style %}
    {% block title%}
    <title>畅销榜</title>
    {% endblock title %}
</head>
<body>
{% block main %}
<main>

</main>
{% endblock main%}
</body>
</html>

bookstore/index/templates/index/订阅榜.html
{% extends 'index/base.html' %}
<html lang="en">
<head>
    <meta charset="UTF-8">
        {% block style %}
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'index/base_style.css' %}">
    <link rel="icon" href="{% static 'index/images/学校.ico' %}">
    {% endblock style %}
    {% block title%}
    <title>订阅榜</title>
    {% endblock title %}
</head>
<body>
{% block main %}
<main>

</main>
{% endblock main%}
</body>
</html>